### PR TITLE
Add gfortran build options for all models supported by OCEAN-LETKF

### PR DESCRIPTION
**Pull request by cd10kfsu**
1. Add gfortran build options for models supported by OCEAN-LETKF (LOCAL_GFORTRAN.*.sh under config/).
2. fix bugs identified by gfortran (i.e., mostly STOP, and FMT required by WRITE statement), and update `make_letkf.model.sh` and `make_obsop.model.sh` under build/
3. building test passes for the models listed below with gfortran 
    - mom6
    - mom6_dynamic
    - mom4
    - hycom
    - hycom_nrl
    - roms
    - sis
    - cice5
    - nemo

### CODE REVIEW

**Review by StevePny — APPROVED** [review]
@cd10kfsu I noticed one place in "config/LOCAL_GFORTRAN.bufr.sh" that uses a hard-coded directory. Ideally that would be generalized, but I think it's ok for now.

**Comment by cd10kfsu** [comment]
@StevePny Thanks for the suggestions Steve! 
The BUFR lib is used by **hycom** obsop when compiling `obsop_bufr_tprof_hycom.f90` and `obsop_bufr_sprof_hycom.f90`.

I can include a script to build BUFR lib inside OCEAN-LETKF, and use it to build **hycom* obsop.

For how to build BUFR lib, I have two options in mind:
1. include a copy of BUFR lib source codes under `/support/bufrlib_[version]` and then build BUFR lib when building `obsop.hycom`
   - pros: which makes the OCEAN-LETKF completely stand-alone, and easier for new users. 
   - cons: (1) it adds 1.6MB to the repo. (2) bufrlib is not updated (though I use v10.2.3 on local and never update it)
2. add a submodule or pull BUFR lib source codes from other repos and then build BUFR lib when building `obsop.hycom`
   - pros: (1) keeps the repo small, (2) bufrlib is always updated
   - cons: bufrlib repo like https://github.com/NOAA-EMC/NCEPLIBS-bufr is growing more heavily, and user will need to specify more options "config/LOCAL_GFORTRAN.bufr.sh", which adds more burden to new users with limited knowledge of building packages

Which option do you think is more appropriate? Thanks!

**Comment by gmao-cda** [comment]
BUFRLIBS included in da42eb4

**Comment by cd10kfsu** [comment]
bufrlibs included in da42eb4

**Pull request merged**
