### PR TITLE
Fix unallocated array and T-cell lat/lon calc.

### PR DESCRIPTION
**Pull request by cd10kfsu**
## Brief description
Fix unallocated array, Loop index for area_t calculation, and T-cell lat/lon calculation for MOM6-LETKF ifdef DYNAMIC

## Features added
1. Add config files for ESSIC server: measures1.umd.edu, and a script to create config template files

## Bugs fixed
1. Allocate missing vars ifdef DYNAMIC
2. Correct loop index for area_t calculation
3. Fix calculation of lat/lon of T-cells from supergrids x,y
4. Increase character length of file and vars names for flexibility

## Test changes
N/A

## Documentation changes
N/A

## Does this create a breaking change?
N/A

### CODE REVIEW

**Comment by StevePny** [comment]
@cd10kfsu After the comments are addressed, I'll merge this PR. But in the future I think it would be good to break up the modifications for each individual bug and any new features that are added into separate PR's.

**Comment by StevePny** [comment]
@cd10kfsu Also, please reference the tag for issue #130 so it closes out when this PR is merged.

**Comment by cd10kfsu** [comment]
> @cd10kfsu After the comments are addressed, I'll merge this PR. But in the future I think it would be good to break up the modifications for each individual bug and any new features that are added into separate PR's.

Thanks @StevePny. I will separate the bug fixes and new features, and then require a separate PR.
Please ignore this one.

**Comment by cd10kfsu** [comment]
Replace this PR with PR #132, which only performs the bugfix for MOM6-LETKF ifdef DYNAMIC (issue #130)

**Pull request closed without merging**
