### PR TITLE
Add CI tests for obsop of MOM6-LEKTF (resolve #137)

### LINKED ISSUE #137: Add obsop running test with OCEAN-LETKF-Data
label with "enhancement"

Create `obsop` running test by hooking the repo https://github.com/cd10kfsu/Ocean-LETKF-Data

### PR DESCRIPTION
**Pull request by cd10kfsu**
## Brief description
Add tests for obsop_sst_geostationary and obsop_sss with the MOM6-LETKF test data from https://github.com/gmao-cda/MOM6-LETKF-Data.git  (resolve #137)

## Features added
1.  Create MOM6-LETKF test data repo at https://github.com/gmao-cda/MOM6-LETKF-Data.git. (No github lfs)
2. Add `test_obsop_sst_geo_msg01.sh` for L2 MSG01 SST.
3. Add `test_obsop_sst_geo_g16_abi.sh` for L2 GOES-16 ABI SST.
4. Add `test_obsop_sss_l2.sh` for L2 SMAP SSS.
5. Add `test_obsop_sss_l3.sh` for L3 SMAP SSS.

## Test changes
1. Add workflow `test_obsop` for testing obsop:
   1. Add 2 tests for obsop_sst_geostationary (L2 MSG01, and GOES-16 ABI SST).
   2. Add 2 tests for obsop_sst (L2 & L3 SMAP SSS).

## Documentation changes
N/A

## Does this create a breaking change?
N/A

### CODE REVIEW

**Comment by cd10kfsu** [comment]
Hi @StevePny, can you review this PR when you have time? Thanks!

**Review by StevePny — APPROVED** [review]

**Comment by sanAkel** [comment]
@StevePny, I am going to merge this. Okay?

**Comment by cd10kfsu** [comment]
@sanAkel you can ignore this PR, and I will prepare a more complete one

**Comment by sanAkel** [comment]
> @sanAkel you can ignore this PR, and I will prepare a more complete one

In that case, please close it yourself with ⬆️ note. Thanks!

**Pull request closed without merging**
